adding some script updates

diff --git a/chef-repo/cookbooks/oba/templates/default/builder/update_cron.sh.erb b/chef-repo/cookbooks/oba/templates/default/builder/update_cron.sh.erb
--- a/chef-repo/cookbooks/oba/templates/default/builder/update_cron.sh.erb
+++ b/chef-repo/cookbooks/oba/templates/default/builder/update_cron.sh.erb
@@ -4,10 +4,19 @@ report_error() {
   aws ses send-email \
 --from no.reply.onebusaway@gmail.com \
 --destination "{ \"ToAddresses\": [\"sbrown@camsys.com\"], \"CcAddresses\": [], \"BccAddresses\": []}" \
---message "{ \"Subject\": { \"Data\": \"PROD FAIL: $1\", \"Charset\": \"UTF-8\"}, \"Body\": {\"Text\": {\"Data\": \"prod Error: $1\"}}}"
+--message "{ \"Subject\": { \"Data\": \"DEV FAIL: $1\", \"Charset\": \"UTF-8\"}, \"Body\": {\"Text\": {\"Data\": \"Dev Error: $1\"}}}"
   echo "issue $1"
-  exit 1
+  #exit 1
 }
+report_finish() {
+  aws ses send-email \
+--from no.reply.onebusaway@gmail.com \
+--destination "{ \"ToAddresses\": [\"sbrown@camsys.com\"], \"CcAddresses\": [], \"BccAddresses\": []}" \
+--message "{ \"Subject\": { \"Data\": \"DEV COMPLETE: $1\", \"Charset\": \"UTF-8\"}, \"Body\": {\"Text\": {\"Data\": \"Dev COMPLETE: $1 ${2} \"}}}"
+  echo "issue $1"
+  #exit 1
+}
+
 
 if ! [ -x "$(command -v aws)" ]
 then
@@ -16,10 +25,12 @@ then
   apt-get install awscli -y
 fi
 
+SECONDS=0
 mount /dev/xvdf /var/lib/oba || report_error "mount failed"
 /sbin/swapon /var/lib/oba/swapfile2 || report_error "swapon failed"
 /usr/sbin/service tomcat7 stop
 /usr/sbin/service tomcat7-watchdog stop
-sudo -u ubuntu /var/lib/oba/transitime/processGTFS/update_from_staged.sh  || report_error "update failed"
+sudo -u ubuntu /var/lib/oba/transitime/processGTFS/update_from_staged.sh  ; report_finish "Elapsed time: ${SECONDS}s" "$(mysql -N -u transitime -pchangeme --host=db.dev.wmata.obaweb.org transitime -e 'select max(configRev) as configRev, processedTime from ConfigRevision;' | tr '[\t]' '[\ ]')"
+
 sleep 600
 /sbin/shutdown -h now
